/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lamborghini_aventador.glb 
Author: Arion Digital (https://sketchfab.com/andrewswihart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-aventador-888e37a3641d4f7b94bc1a39396e2441
Title: Lamborghini Aventador
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'


export function Lamborghini_aventador(props) {
  const { nodes, materials } = useGLTF('/models/lamborghini_aventador.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body_Lamborginhi_base_phong_0.geometry} material={materials.Lamborginhi_base_phong} />
      <mesh geometry={nodes.Glass_Lamborginhi_glass_phong_0.geometry} material={materials.Lamborginhi_glass_phong} />
      <mesh geometry={nodes.Wheel_FL_Lamborginhi_base_phong_0.geometry} material={materials.Lamborginhi_base_phong} />
      <mesh geometry={nodes.Wheel_FR_Lamborginhi_base_phong_0.geometry} material={materials.Lamborginhi_base_phong} />
      <mesh geometry={nodes.Wheel_RL_Lamborginhi_base_phong_0.geometry} material={materials.Lamborginhi_base_phong} />
      <mesh geometry={nodes.Wheel_RR_Lamborginhi_base_phong_0.geometry} material={materials.Lamborginhi_base_phong} />
    </group>
  )
}

useGLTF.preload('/models/lamborghini_aventador.glb')

export default Lamborghini_aventador;
